# Dependencies
markdown:         kramdown
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            'Richard E.W. Berl'
description:      'Cultural evolution.<br>Social learning.<br>Data science.<br>Dad.'
url:              http://rewberl.github.io
baseurl:          /

author:
  name:           'Richard E.W. Berl'
  url:            http://rewberl.github.io

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rewberl/rewberl.github.io

# Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
