# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Richard E.W. Berl'
tagline:          'Me'
description:      'Researcher in the transmission and evolution of culture in humans and non-human animals. Also a dad and data scientist-in-training.'
url:              http://rewberl.github.io
baseurl:          /

author:
  name:           'Richard E.W. Berl'
  url:            http://rewberl.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rewberl/rewberl.github.io
  
# Gems
gems: [jekyll-paginate]